CREATE TABLE IF NOT EXISTS USER (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name VARCHAR(20),
    Surname VARCHAR(20),
    BirthDate DATE,
    Address VARCHAR(30),
    PhoneNumber VARCHAR(20),
    Email VARCHAR(30),
    Username VARCHAR(30) NOT NULL UNIQUE,
    Password VARCHAR(30) NOT NULL,
    FiscalCode CHAR(16) UNIQUE,
    UserType VARCHAR(10) CHECK ( UserType IN ('Doctor','Patient','Admin')) 
);

CREATE TABLE IF NOT EXISTS PATIENT_CLINICALDATA (
    IdPatient INTEGER PRIMARY KEY,
    Height REAL,
    Weight REAL,
    Gender CHAR(1) CHECK ( Gender IN ('M','F')),
    RiskCode INTEGER,
    IdAdmin INTEGER NOT NULL,
    IdWearable INTEGER,
    LastUpdate DATE,
    FOREIGN KEY (IdPatient) REFERENCES USER(Id),
    FOREIGN KEY (IdAdmin) REFERENCES ADMIN(IdAdmin),
    FOREIGN KEY (IdWearable) REFERENCES WEARABLE(IdWearable)
);

CREATE TABLE IF NOT EXISTS DOCTOR (
    IdDoctor INTEGER PRIMARY KEY, 
    IdAdmin INTEGER NOT NULL,
    FOREIGN KEY (IdAdmin) REFERENCES ADMIN(IdAdmin)
);

 CREATE TABLE IF NOT EXISTS ADMIN( 
   IdAdmin INTEGER PRIMARY KEY,
   FOREIGN KEY (IdAdmin) REFERENCES USER (Id)
);

CREATE TABLE IF NOT EXISTS SUPPORT (
    IdSupport INTEGER PRIMARY KEY AUTOINCREMENT,
    Date DATE,
    SupportType VARCHAR(20) CHECK (SupportType IN ('SupportCredentials','InconsistentData','Wearable','ScheduleIssue','Others' )),
    IdRequester INTEGER NOT NULL,
    IdAdmin INTEGER NOT NULL,
    Message TEXT,
    FOREIGN KEY (IdRequester) REFERENCES USER(Id),
    FOREIGN KEY (IdAdmin) REFERENCES ADMIN(IdAdmin)
);

CREATE TABLE IF NOT EXISTS THERAPY (
    IdTherapy INTEGER PRIMARY KEY AUTOINCREMENT,
    Date DATE,
    Description VARCHAR(300),
    IdDoctor INTEGER NOT NULL,
    IdPatient INTEGER NOT NULL,
    FOREIGN KEY (IdDoctor) REFERENCES DOCTOR(IdDoctor),
    FOREIGN KEY (IdPatient) REFERENCES PATIENT_CLINICALDATA(IdPatient)
);

CREATE TABLE IF NOT EXISTS THR_PERSONALIZED (
    IdPatient INTEGER PRIMARY KEY,
    ThresholdSBP REAL DEFAULT 120,
    ThresholdDBP REAL DEFAULT 80,
    ThresholdSpO2 REAL DEFAULT 92,
    ThresholdUpperHeartRate REAL DEFAULT 150,
    ThresholdLowerHeartRate REAL DEFAULT 40,
    FOREIGN KEY (IdPatient) REFERENCES PATIENT_CLINICALDATA(IdPatient)
);

CREATE TABLE IF NOT EXISTS APPOINTMENT (
    IdAppointment INTEGER PRIMARY KEY AUTOINCREMENT,
    Date DATE,
    Time TIME, 
    Notes VARCHAR(500),
    IdPatient INTEGER NOT NULL,
    IdDoctor INTEGER NOT NULL,
    FOREIGN KEY (IdPatient) REFERENCES PATIENT_CLINICALDATA(IdPatient),
    FOREIGN KEY (IdDoctor) REFERENCES DOCTOR(IdDoctor)
);

CREATE TABLE IF NOT EXISTS WEARABLE_DEVICE (
    IdWearable INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE IF NOT EXISTS DATA (
    IdData INTEGER PRIMARY KEY AUTOINCREMENT, 
    NameData VARCHAR(20) CHECK ( NameData IN ('SBP','DBP','StepCount','SleepQualityIndex','Weight','SleepHours','ECG','HR','VO2Max','SPO2')),
    Date DATE,
    IdPatient INTEGER NOT NULL,
    IdWearable INTEGER NOT NULL,
    FOREIGN KEY (IdPatient) REFERENCES PATIENT_CLINICALDATA(IdPatient),
    FOREIGN KEY (IdWearable) REFERENCES WEARABLE_DEVICE(IdWearable)
);

CREATE TABLE IF NOT EXISTS NUMERICAL_DATA (
    IdNumData INTEGER PRIMARY KEY,
    Date DATE,
    Max REAL,
    Min REAL,
    Mean REAL,
    DayTime VARCHAR(5) CHECK (DayTime IN ('Day','Night')),
    FOREIGN KEY (IdNumData) REFERENCES DATA(IdData)
);

CREATE TABLE IF NOT EXISTS SIGNALS (
    IdSignals INTEGER PRIMARY KEY,
    Value BLOB,
    Sampling_Freq INTEGER,
    Time TIME,
    FOREIGN KEY (IdSignals) REFERENCES DATA(IdData)
);

CREATE TABLE IF NOT EXISTS NOTIFICATION (
    IdNotification INTEGER PRIMARY KEY AUTOINCREMENT,
    IdSender INTEGER NOT NULL,
    IdReceiver INTEGER NOT NULL,
    Message VARCHAR(500),
    IsRead BOOLEAN DEFAULT 0,
    Date DATE,
    Time TIME,
    FOREIGN KEY (IdSender) REFERENCES USER(Id),
    FOREIGN KEY (IdReceiver) REFERENCES USER(Id)
);

CREATE TABLE IF NOT EXISTS CHECK_OUT ( 
   IdAppointment INTEGER PRIMARY KEY,
   ReportPath VARCHAR(100),
   FOREIGN KEY (IdAppointment) REFERENCES APPOINTMENT (IdAppointment) 
);

CREATE TABLE IF NOT EXISTS PATHOLOGY (
    IdPathology INTEGER PRIMARY KEY AUTOINCREMENT,
    Name VARCHAR(50) NOT NULL,
    Code VARCHAR(6) UNIQUE NOT NULL
);

CREATE TABLE USER_PATHOLOGIES (
    IdPatient INT,
    IdPathology INTEGER,
    Date DATE,
    FOREIGN KEY (IdPatient) REFERENCES PATIENT_CLINICALDATA(IdPatient),
    FOREIGN KEY (IdPathology) REFERENCES PATHOLOGY(IdPathology),    
    PRIMARY KEY (IdPatient, IdPathology)
);
